import {useState} from 'react';
import Brand from './Brand';
import Admissions from './Admissions';
import {majors} from './student';
type Props={signedIn:boolean;onEnter:(view?:'campus'|'majors'|'courses')=>void;onSignup:()=>void;onLogin:()=>void};
export default function FrontPage({signedIn,onEnter,onSignup,onLogin}:Props){
 const [discipline,setDiscipline]=useState(0);const [menu,setMenu]=useState(false);const [interest,setInterest]=useState<number|null>(null);const [admissions,setAdmissions]=useState<'apply'|'portal'|null>(null);
 const selected=majors[discipline];
 if(admissions)return <Admissions mode={admissions} onClose={()=>setAdmissions(null)} onCreateAccount={onSignup} onLogin={onLogin}/>;
 return <main className="unity-front">
  <a href="#main-content" className="unity-skip">Skip to content</a>
  <header className="front-nav"><a href="#" aria-label="Lumi University home"><Brand/></a><button className="front-menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'open':''} aria-label="Website navigation"><a href="#find-your-path" onClick={()=>setMenu(false)}>Academics</a><a href="#campus-life" onClick={()=>setMenu(false)}>Campus Life</a><button onClick={()=>{setAdmissions('portal');setMenu(false);}}>Admissions</button><a href="#tuition-aid" onClick={()=>setMenu(false)}>Tuition & Aid</a></nav><div className="front-nav-actions">{signedIn?<button className="front-button light" onClick={()=>onEnter()}>My campus ↗</button>:<><button className="front-login" onClick={onLogin}>Sign in</button><button className="front-button lime" onClick={()=>setAdmissions('apply')}>Apply ↗</button></>}</div></header>
  <section className="front-hero" id="main-content"><div className="front-hero-copy"><p className="front-eyebrow"><span/> AN AI UNIVERSITY BY BIJOU NICOLE</p><h1>Your future<br/>has room<br/><em>to grow.</em></h1><p className="front-intro">Build a degree path around what you want to become. Explore creative majors, learn with Lumi, and move from applicant to student in one connected university experience.</p><div className="front-hero-actions"><button className="front-button lime" onClick={signedIn?()=>onEnter():()=>setAdmissions('apply')}>{signedIn?'Continue your journey':'Apply to Lumi University'} <span>↗</span></button><a href="#find-your-path">Explore academics <span>↓</span></a></div><div className="front-facts"><span>AI-powered learning</span><span>Your major. Your pathway.</span></div></div><div className="front-hero-visual"><img className="front-studio-image" src="/lumi/unity-creative-studio.webp" alt="Students creating together in a modern Lumi University studio"/><div className="front-image-caption"><span>LEARN. BUILD. BECOME.</span><strong>A university experience<br/>made around you.</strong></div><button className="front-explore-chip" onClick={()=>setAdmissions('apply')}><span>✦</span><div>Applications are open.<small>Start your application</small></div><b>↘</b></button></div></section>
  <div className="front-ribbon" aria-label="University experience"><span>Personalized majors</span><i>✦</i><span>AI academic support</span><i>✦</i><span>Interactive campus life</span><i>✦</i><span>Built by Bijou Nicole</span></div>
  <section className="front-paths" id="find-your-path"><div className="front-section-heading"><div><p className="front-eyebrow">ACADEMICS</p><h2>Choose the path<br/>that feels like yours.</h2></div><p>Your major shapes your courses, practice studio,<br/>degree audit, Lumi guidance, and graduation plan.</p></div><div className="front-path-tabs" role="tablist" aria-label="Explore majors">{majors.map((m,i)=><button key={m.id} id={`major-tab-${i}`} role="tab" aria-selected={discipline===i} aria-controls="major-preview" onClick={()=>setDiscipline(i)}>{['Music','Visual arts','Film'][i]} <span>0{i+1}</span></button>)}</div><article className={`front-major-preview path-${discipline}`} role="tabpanel" id="major-preview" aria-labelledby={`major-tab-${discipline}`}><div className="front-major-number" aria-hidden="true">0{discipline+1}<span>{['MAKE SOME NOISE.','MAKE THEM LOOK.','MAKE THEM FEEL.'][discipline]}</span></div><div className="front-major-copy"><p className="front-eyebrow">{selected.school}</p><h3>{selected.degree}</h3><p>{selected.description}</p><ul>{selected.outcomes.map(o=><li key={o}>↗ {o}</li>)}</ul><div className="front-hero-actions"><button className="front-button ink" onClick={()=>onEnter('majors')}>Explore this major ↗</button><button className="front-button lime" onClick={()=>setAdmissions('apply')}>Apply to this program ↗</button></div></div></article></section>
  <section className="front-learning" id="learn-your-way"><div><p className="front-eyebrow">HOW YOU’LL LEARN</p><h2>AI support built<br/>into your campus.</h2><p>Lumi lives inside the student experience. Once you are enrolled, it can help explain coursework, practice weak concepts, support degree planning, and stay focused on the student service you selected.</p><div className="front-learning-steps"><div><b>01</b><span><strong>Your major sets the path</strong><small>Courses and practice follow your program automatically.</small></span></div><div><b>02</b><span><strong>Lumi learns the context</strong><small>Ask for help inside a lesson, service, or degree-planning screen.</small></span></div><div><b>03</b><span><strong>Your progress stays together</strong><small>My Major, grades, practice, and degree audit stay connected.</small></span></div></div></div><div className="front-lesson-demo"><div className="front-demo-label"><span>✦ LUMI / STUDENT EXPERIENCE</span><small>Available after enrollment</small></div><h3>No guest demo.</h3><p>Prospective students can explore the university publicly, but personalized lessons, practice, Lumi tutoring, grades, and degree planning stay inside the student account.</p><div className="front-demo-answer"><strong>Already a student?</strong><p>Sign in to return to your saved coursework and campus.</p><button onClick={onLogin}>Student sign in ↗</button></div></div></section>
  <section className="front-finder"><div><p className="front-eyebrow">NOT SURE WHAT TO STUDY?</p><h2>What would you<br/>love to make?</h2><p>Start with what pulls you. Your answer can point you toward a program.</p></div><div className="front-finder-options">{['A song people feel','A visual world people remember','A story people can see'].map((t,i)=><button key={t} aria-pressed={interest===i} onClick={()=>setInterest(i)}><span>0{i+1}</span>{t}<b>↗</b></button>)}{interest!==null&&<div className="front-finder-result" role="status"><p>Take a closer look at <strong>{majors[interest].degree}</strong>.</p><button className="front-button lime" onClick={()=>{setDiscipline(interest);document.getElementById('find-your-path')?.scrollIntoView({behavior:'smooth'});}}>Show me the major ↑</button></div>}</div></section>
  <section className="front-paths" id="campus-life"><div className="front-section-heading"><div><p className="front-eyebrow">CAMPUS LIFE</p><h2>More than classes.<br/>A whole university world.</h2></div><p>Residence halls, student spaces, creative studios,<br/>events, wellness, and an interactive campus experience.</p></div><div className="front-major-preview path-1"><div className="front-major-number" aria-hidden="true">4D<span>EXPLORE THE CAMPUS.</span></div><div className="front-major-copy"><p className="front-eyebrow">RESIDENCE LIFE + CAMPUS</p><h3>See where student life happens.</h3><p>Campus Life is being built as an interactive environment where students can explore residence halls, room styles, academic spaces, the student union, library, recreation, wellness, and creative facilities.</p><ul><li>↗ Single, double, suite, and apartment-style residence plans</li><li>↗ Interactive dorm and campus exploration</li><li>↗ Student events and campus announcements</li></ul><button className="front-button ink" onClick={()=>onEnter()}>Open campus experience ↗</button></div></div></section>
  <section className="front-faq" id="tuition-aid"><div><p className="front-eyebrow">TUITION & AID</p><h2>Plan the money side<br/>with clarity.</h2></div><div><details open><summary>Financial aid interest on your application<span>＋</span></summary><p>Your application now includes a financial-aid interest option so future aid guidance and admitted-student steps can be personalized. Lumi should never ask for bank passwords or private financial login details.</p></details><details><summary>Housing planning<span>＋</span></summary><p>Applicants can also mark interest in campus housing. Accepted students can later receive residence-life steps as part of enrollment onboarding.</p></details><details><summary>Published tuition and aid amounts<span>＋</span></summary><p>Official tuition, aid awards, scholarships, and payment schedules should only appear once Lumi University has approved and published those figures. The site will not invent an award or promise funding.</p></details></div></section>
  <section className="front-faq" id="unity-questions"><div><p className="front-eyebrow">ADMISSIONS</p><h2>Your application,<br/>all in one place.</h2></div><div>{[['How do I apply?','Use the Apply button to complete About You, Contact, Education History, Choose Your Major, Personal Statement, Plans, and Review & Submit. Your application saves on your device as you go.'],['What happens after I submit?','You move into the Applicant Portal, where your application ID, selected program, checklist, submitted status, and eventual admission decision live together.'],['Can I come back to my application?','Yes. Use Applicant Portal in the Admissions area to return to the application saved on this device.'],['What happens if I am accepted?','The admitted-student portal includes an Accept Admission action that begins student-account setup and enrollment onboarding.'],['Do prospective students get a lesson demo?','No. Public visitors can explore majors, admissions, campus life, and university information. Personalized Lumi learning tools stay inside enrolled student accounts.']].map(([q,a])=><details key={q}><summary>{q}<span>＋</span></summary><p>{a}</p></details>)}</div></section>
  <section className="front-final-cta"><p className="front-eyebrow">YOUR APPLICATION STARTS HERE.</p><h2>Picture yourself here.<br/>Then make it real.</h2><div className="front-hero-actions" style={{justifyContent:'center'}}><button className="front-button lime" onClick={signedIn?()=>onEnter():()=>setAdmissions('apply')}>{signedIn?'Open my campus':'Apply to Lumi University'} ↗</button>{!signedIn&&<button className="front-button light" onClick={()=>setAdmissions('portal')}>Applicant Portal ↗</button>}</div></section>
  <footer className="front-footer"><Brand/><p>An AI university by Bijou Nicole.<br/>Built for your next chapter.</p><div><button onClick={()=>onEnter('majors')}>Academics</button><button onClick={()=>setAdmissions('portal')}>Admissions</button><button onClick={()=>setAdmissions('apply')}>Apply</button><button onClick={()=>onEnter()}>Student campus</button></div><small>Lumi University · AI-powered higher-learning experience</small></footer>
 </main>;
}
