import {useState} from 'react';
import Brand from './Brand';
import {majors} from './student';
import {courses} from './learning';
type Props={signedIn:boolean;onEnter:(view?:'campus'|'majors'|'courses')=>void;onSignup:()=>void;onLogin:()=>void};
export default function FrontPage({signedIn,onEnter,onSignup,onLogin}:Props){
 const [discipline,setDiscipline]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [menu,setMenu]=useState(false);const [interest,setInterest]=useState<number|null>(null);
 const selected=majors[discipline];const sample=courses.find(c=>c.id===selected.courseIds[0])!.lessons[0];
 return <main className="unity-front">
  <a href="#main-content" className="unity-skip">Skip to content</a>
  <header className="front-nav"><a href="#" aria-label="Unity home"><Brand/></a><button className="front-menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'open':''} aria-label="Website navigation"><a href="#find-your-path" onClick={()=>setMenu(false)}>Our majors</a><a href="#learn-your-way" onClick={()=>setMenu(false)}>How you’ll learn</a><a href="#unity-questions" onClick={()=>setMenu(false)}>Good to know</a></nav><div className="front-nav-actions">{signedIn?<button className="front-button light" onClick={()=>onEnter()}>My campus ↗</button>:<><button className="front-login" onClick={onLogin}>Log in</button><button className="front-button lime" onClick={onSignup}>Join Unity ↗</button></>}</div></header>
  <section className="front-hero" id="main-content"><div className="front-hero-copy"><p className="front-eyebrow"><span/> A COLLEGE OF CREATIVE POSSIBILITIES</p><h1>You’ve got<br/>something<br/><em>in you.</em></h1><p className="front-intro">Give it a place to grow. Explore music, visual arts, and film—with a learning path of your own and Lumi by your side.</p><div className="front-hero-actions"><button className="front-button lime" onClick={signedIn?()=>onEnter():onSignup}>{signedIn?'Continue your journey':'Find your beginning'} <span>↗</span></button><a href="#find-your-path">Explore the majors <span>↓</span></a></div><div className="front-facts"><span>100% online learning</span><span>Your pace. Your perspective.</span></div></div><div className="front-hero-visual"><img className="front-studio-image" src="/lumi/unity-creative-studio.webp" alt="Creative students making music, visual art, and film together in a studio"/><div className="front-image-caption"><span>THINK IT. TRY IT. MAKE IT.</span><strong>A little curiosity<br/>can change everything.</strong></div><a className="front-explore-chip" href="#learn-your-way"><span>✦</span><div>Meet your creative side.<small>Try a little lesson below</small></div><b>↘</b></a></div></section>
  <div className="front-ribbon" aria-label="Creative disciplines"><span>Music & songwriting</span><i>✦</i><span>Visual arts</span><i>✦</i><span>Film & storytelling</span><i>✦</i><span>Made of possibility</span></div>
  <section className="front-paths" id="find-your-path"><div className="front-section-heading"><div><p className="front-eyebrow">FOLLOW WHAT PULLS YOU</p><h2>Different paths.<br/>The same creative spark.</h2></div><p>You don’t have to have it all figured out.<br/>Start with what makes you curious.</p></div><div className="front-path-tabs" role="tablist" aria-label="Explore creative majors">{majors.map((m,i)=><button key={m.id} id={`major-tab-${i}`} role="tab" aria-selected={discipline===i} aria-controls="major-preview" onClick={()=>{setDiscipline(i);setChoice(null);}} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:2))%3;setDiscipline(next);setChoice(null);document.getElementById(`major-tab-${next}`)?.focus();}}}>{['Music','Visual arts','Film'][i]} <span>0{i+1}</span></button>)}</div><article className={`front-major-preview path-${discipline}`} role="tabpanel" id="major-preview" aria-labelledby={`major-tab-${discipline}`}><div className="front-major-number" aria-hidden="true">0{discipline+1}<span>{['MAKE SOME NOISE.','MAKE THEM LOOK.','MAKE THEM FEEL.'][discipline]}</span></div><div className="front-major-copy"><p className="front-eyebrow">{selected.school}</p><h3>{selected.title}</h3><p>{selected.description}</p><ul>{selected.outcomes.map(o=><li key={o}>↗ {o}</li>)}</ul><button className="front-button ink" onClick={()=>onEnter('majors')}>Explore this path ↗</button></div></article></section>
  <section className="front-learning" id="learn-your-way"><div><p className="front-eyebrow">LESS SCROLLING. MORE DISCOVERY.</p><h2>Learning that<br/>moves with you.</h2><p>Lumi is built right into Unity. Work through a concept, ask a question, try something new, and return to the conversation when you’re ready.</p><div className="front-learning-steps"><div><b>01</b><span><strong>A place to start</strong><small>Short lessons, clear ideas, creative examples.</small></span></div><div><b>02</b><span><strong>Room to figure it out</strong><small>Ask Lumi to slow down or explain another way.</small></span></div><div><b>03</b><span><strong>Something you made</strong><small>Turn your learning into a personal project.</small></span></div></div></div><div className="front-lesson-demo"><div className="front-demo-label"><span>✦ LUMI / A LITTLE TASTE</span><small>Interactive sample</small></div><h3>{sample.title}</h3><p>{sample.question}</p><fieldset><legend className="unity-sr-only">Choose your answer</legend>{sample.options.map((option,i)=><button type="button" aria-pressed={choice===i} className={choice===i?'chosen':''} key={option} onClick={()=>setChoice(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</fieldset>{choice!==null?<div role="status" className="front-demo-answer"><strong>{choice===sample.answer?'You’ve got it.':'Let’s take another look.'}</strong><p>{sample.explanation}</p><button onClick={()=>onEnter('courses')}>Keep exploring ↗</button></div>:<p className="front-demo-hint">Pick an answer. Curiosity looks good on you.</p>}</div></section>
  <section className="front-finder"><div><p className="front-eyebrow">NOT SURE WHERE TO START?</p><h2>What would you<br/>love to make?</h2><p>No wrong answers. Just a starting point.</p></div><div className="front-finder-options">{['A song people feel','A visual world people remember','A story people can see'].map((t,i)=><button key={t} aria-pressed={interest===i} onClick={()=>setInterest(i)}><span>0{i+1}</span>{t}<b>↗</b></button>)}{interest!==null&&<div className="front-finder-result" role="status"><p>Start exploring <strong>{majors[interest].title}</strong>.</p><button className="front-button lime" onClick={()=>{setDiscipline(interest);setChoice(null);document.getElementById('find-your-path')?.scrollIntoView({behavior:'smooth'});}}>Show me my starting point ↑</button></div>}</div></section>
  <section className="front-faq" id="unity-questions"><div><p className="front-eyebrow">GOOD TO KNOW</p><h2>A few things<br/>before you begin.</h2></div><div>{[['What can I study right now?','Our foundation collection covers music and songwriting, visual arts and creative direction, and film and digital storytelling. Each major combines two foundation courses with creative project briefs.'],['Do I need creative experience?','You can start with the foundations. Lessons are self-paced, and you can ask Lumi for simpler explanations, another example, or a more challenging exercise.'],['What is Lumi?','Lumi is Unity’s built-in AI learning companion. It helps you work through lessons and projects; its feedback is guidance, not an instructor-issued grade.'],['Will I earn an accredited degree?','Unity currently offers self-paced foundation learning, not accredited degrees or transferable academic credits. Practice GPA and downloadable learning records are personal study tools.'],['How do I get started?','Create a student account, choose a major, and open your campus. Your major shapes your learning path. Sign in to sync your work between devices.']].map(([q,a])=><details key={q}><summary>{q}<span>＋</span></summary><p>{a}</p></details>)}</div></section>
  <section className="front-final-cta"><p className="front-eyebrow">THE NEXT CHAPTER IS YOURS.</p><h2>Come as you are.<br/>Create what’s next.</h2><button className="front-button lime" onClick={signedIn?()=>onEnter():onSignup}>{signedIn?'Open my campus':'Start your Unity journey'} ↗</button></section>
  <footer className="front-footer"><Brand/><p>A creative learning space by Bijou.<br/>Built for your next chapter.</p><div><button onClick={()=>onEnter('majors')}>Majors</button><button onClick={()=>onEnter()}>Student campus</button><a href="#unity-questions">About your learning</a></div><small>Unity College of the Arts · Foundation learning</small></footer>
 </main>;
}
