export type Lesson = { title: string; minutes: number; body: string[]; exercise: string; question: string; options: string[]; answer: number; explanation: string };
export type Course = { id: string; code: string; title: string; discipline: string; color: string; description: string; project: string; criteria: string[]; lessons: Lesson[] };
export const courses: Course[] = [
 { id:'songwriting',code:'MUS 101',title:'Songwriting & storytelling',discipline:'Music',color:'blue',description:'Find the story. Shape the hook. Make every line earn its place.',project:'Write a verse and chorus that tell one moment from two emotional angles. Add a short note explaining what changes between them.',criteria:['A clear point of view','Specific sensory detail','A chorus that develops the central idea'],lessons:[
 {title:'Find your point of view',minutes:8,body:['A song’s narrator is the voice telling the story. Decide who is speaking, who they are addressing, and what they want. Your narrator can be you or a character; the listener needs a consistent perspective.','Compare “I miss you” with “Your coffee cup is still beside the sink.” The first names an emotion. The second gives the listener a concrete detail from which to feel it. Both have a place; choosing deliberately creates contrast.'],exercise:'Write four lines about someone leaving. Include one object, one action, and one detail you can hear. Keep the same narrator.',question:'Which choice gives a listener a concrete image?',options:['I feel so lonely','Your jacket hangs beside the door','Everything is emotional'],answer:1,explanation:'The jacket and door create a visible scene. The other lines name feelings without a specific image.'},
 {title:'Build a chorus that lands',minutes:10,body:['A chorus returns to the song’s central idea. Its words and melodic shape often repeat so the listener can recognize it. A verse can supply new events while the chorus reveals what those events mean.','A hook is a memorable phrase or musical idea. Write a short central phrase, then try it at the beginning and end of a chorus. Repetition works best when each surrounding line strengthens the same idea.'],exercise:'Choose a four-to-eight-word hook. Draft four chorus lines around it, then speak them aloud to check natural stress.',question:'What is a useful job for a chorus?',options:['Introduce unrelated characters every time','Avoid any repeating idea','Return to the central emotional idea'],answer:2,explanation:'A returning central idea helps connect changing verses and gives the listener something recognizable.'},
 {title:'Revise for rhythm and meaning',minutes:12,body:['Read your lyrics aloud before you polish them. Notice syllables that feel crowded and words whose natural stress conflicts with your intended rhythm. Shortening a line can make room for a breath or a held note.','Revise in separate passes: first meaning, then rhythm, then sound. A rhyme is useful when it supports what the narrator would actually say. Keep a strong honest line over a forced rhyme.'],exercise:'Rewrite one line three ways: more specific, fewer syllables, and a different ending sound. Choose the version that best serves the story.',question:'What should guide a revision?',options:['The story and how the line feels aloud','Rhyming every single word','Making every line longer'],answer:0,explanation:'Meaning and delivery work together. More rhyme or more words do not automatically improve a lyric.'}]},
 {id:'visual',code:'ART 110',title:'Visual identity & art direction',discipline:'Visual arts',color:'orange',description:'Turn a creative idea into a visual language with intention.',project:'Write an art-direction brief for an original release: concept, three colors, typography direction, and an image description. Explain how each choice supports the story.',criteria:['One focused concept','A clear visual hierarchy','A reason for each design choice'],lessons:[
 {title:'Start with a creative brief',minutes:7,body:['A creative brief connects a purpose to design choices. Start with the audience, the feeling you want to communicate, and where the work will appear. A cover viewed on a phone has different constraints from a stage backdrop.','Choose three descriptive words with useful tension, such as intimate, restless, and electric. Test every proposed image or type choice against them. References help communicate a direction; create your own work rather than copying a finished design.'],exercise:'Choose an imaginary release. Write its audience, purpose, format, and three visual keywords.',question:'What should a creative brief clarify first?',options:['Every software tool you own','The audience and purpose','The final export filename'],answer:1,explanation:'Audience and purpose give the later visual decisions a clear reason.'},
 {title:'Create a visual hierarchy',minutes:9,body:['Hierarchy tells a viewer what to notice first, second, and third. Scale, contrast, spacing, and placement all help establish that order. When everything competes for attention, nothing feels primary.','For a release poster, try a large title, a quieter artist name, and supporting details with room around them. Test at a small size. If the main message disappears, simplify or increase its contrast.'],exercise:'List a poster’s content in order of importance. Describe the size and placement of each element.',question:'How can you strengthen hierarchy?',options:['Give everything the same emphasis','Add more competing focal points','Make the primary message clearly dominant'],answer:2,explanation:'A dominant primary message gives the viewer an entry point and supports an intentional reading order.'},
 {title:'Build a consistent system',minutes:10,body:['A visual identity is a set of repeatable choices: colors, type styles, image treatment, and spacing. It should work across different formats without requiring every piece to be identical.','Specify which choices stay constant and which can change. For example, keep the title type and core colors, but crop imagery differently for a square cover and a vertical poster. Check that essential text stays readable.'],exercise:'Write three rules that stay consistent across a cover, poster, and social post, plus one thing that may vary.',question:'What makes a visual system useful?',options:['Repeatable choices that adapt to formats','An identical crop everywhere','Using a new typeface on every post'],answer:0,explanation:'Consistency makes the work recognizable; flexibility lets it function in different formats.'}]},
 {id:'film',code:'FLM 100',title:'Film & visual storytelling',discipline:'Film',color:'pink',description:'Think in shots, build a scene, and tell a story through images.',project:'Create a six-shot plan for a one-minute scene about an unexpected arrival. Describe framing, action, sound, and the purpose of each shot.',criteria:['A clear beginning, change, and ending','Purposeful shot choices','Sound that supports the scene'],lessons:[
 {title:'Give the scene a turning point',minutes:8,body:['A scene becomes a story when something changes. Give a character an immediate goal, an obstacle, and a moment that alters what they know or do. A small change can be enough.','A person waiting by a window is an image. A person waiting, hiding a letter when a car arrives, and then choosing to open the door has a sequence of decisions. Show the change through observable action.'],exercise:'Describe a scene in three sentences: what the character wants, what interrupts them, and what they do next.',question:'What gives a scene movement?',options:['Only describing the room','A goal, obstacle, and change','A list of camera brands'],answer:1,explanation:'A goal and obstacle create a reason for action; the change makes that action meaningful.'},
 {title:'Choose the frame',minutes:9,body:['A wide shot establishes space and relationships. A medium shot lets us read action and body language. A close-up directs attention toward an expression or meaningful detail. Choose distance based on what the audience needs to notice.','A shot list records the planned framing and action. It is a thinking tool, not a requirement to use every possible angle. Ask what new information each shot contributes.'],exercise:'Plan a wide shot, medium shot, and close-up for the same arrival. Explain what each reveals.',question:'Which choice best highlights a small meaningful detail?',options:['A distant establishing shot','An unrelated cutaway','A close-up of the detail'],answer:2,explanation:'A close-up concentrates the viewer’s attention on the selected detail.'},
 {title:'Use sound with intention',minutes:10,body:['Sound can belong to the scene’s world, such as a knock or a radio, or come from outside it, such as a score. These are often called diegetic and non-diegetic sound. Either can guide attention and emotion.','Think about what should be heard before it is seen. A car door outside can signal an arrival while the camera stays on the waiting character. A quieter moment can make the next sound more noticeable.'],exercise:'Add three sound cues to your scene. Say where each comes from and when the audience hears it.',question:'Which sound belongs to the scene’s world?',options:['A character knocking on the door','A score only the audience hears','An external narrator’s commentary'],answer:0,explanation:'The knock exists in the scene and can be heard by its characters.'}]}];
export const journalMarker = (id: string) => `[Unity coursework: ${id}]`;
export type JournalMessage = { role: 'user' | 'lumi'; text: string };
export function readJournal(messages: JournalMessage[]) {
 const completed = new Set<string>(); let draft = '';
 for (const message of messages) {
  if(message.role !== 'user') continue;
  if(message.text.startsWith('Completed lesson: ')) completed.add(message.text.slice(18));
  if(message.text.startsWith('Reopened lesson: ')) completed.delete(message.text.slice(17));
  if(message.text.startsWith('Project draft:\n')) draft = message.text.slice(15);
 }
 return {completed,draft};
}

export const lessonMarker = (courseId: string, lessonTitle: string) => `[Unity lesson: ${courseId} / ${lessonTitle}]`;
export function lessonOpening(course: Course, lesson: Lesson, name: string | undefined, completed: string[]): JournalMessage[] {
 const prior = course.lessons.filter(item=>completed.includes(item.title)&&item.title!==lesson.title).map(item=>item.title);
 return [
  {role:'user',text:`${lessonMarker(course.id,lesson.title)}\nYou are Lumi, the AI creative tutor at Unity College of the Arts. Teach this lesson through a warm, concise conversation. Introduce one concept at a time, use original arts examples, ask one question and wait for the learner. Adapt to their answers; do not claim mastery or award official grades. If they are confused, simplify before advancing. Treat the learner's creative work as their own. Provide explanations and brief feedback, never internal reasoning, tool traces, or invented retrieval status. Only reference the supplied completion history; completion is self-reported.\nCourse: ${course.title}\nLesson: ${lesson.title}\nLesson notes: ${lesson.body.join('\n')}\nPractice: ${lesson.exercise}\nKnowledge check: ${lesson.question}\nCorrect concept: ${lesson.explanation}\nPreviously completed lessons: ${prior.join(', ')||'none recorded'}.`},
  {role:'lumi',text:`Welcome${name?`, ${name.split(' ')[0]}`:''} ✦\n\nToday’s studio session: **${lesson.title}**.\n\n${prior.length?`You’ve marked ${prior.length} other lesson${prior.length===1?'':'s'} complete in this course. We’ll build from there.`:'We’ll start with the foundations and take this one idea at a time.'}\n\n${lesson.body[0]}\n\nBefore we try it together: have you explored this before, or would you like to start from scratch?`}
 ];
}
