import {useState} from 'react';
import {courses,type Course,type JournalMessage,readJournal,journalMarker} from './learning';
import {majors,PROFILE_MARKER,attemptsFrom,gradeSummary,services,type Major,type StudentJournal,type Attempt} from './student';

type PortalView='majors'|'practice'|'grades'|'services'|'campus'|'audit';
type Props={view:string;major:Major|null;journals:StudentJournal[];ready:boolean;signedIn:boolean;onSignup:()=>void;onSave:(marker:string,title:string,messages:JournalMessage[])=>void;onOpen:(course:Course)=>void;onHelp:(prompt?:string)=>void;onService:(id:string)=>void;onNavigate:(view:PortalView)=>void};

export default function StudentPortal({view,major,journals,ready,signedIn,onSignup,onSave,onOpen,onHelp,onService,onNavigate}:Props){
 const majorCourses=(major?.courseIds||courses.map(c=>c.id)).map(id=>courses.find(c=>c.id)).filter(Boolean) as Course[];
 const [practiceId,setPracticeId]=useState(majorCourses[0]?.id||courses[0].id);
 const [answers,setAnswers]=useState<Record<number,number>>({});
 const [result,setResult]=useState<Attempt|null>(null);
 const [serviceFilter,setServiceFilter]=useState('all');
 const [pendingMajor,setPendingMajor]=useState(major?.id||'');
 const attempts=attemptsFrom(journals);
 const summary=gradeSummary(attempts,major?.courseIds||courses.map(c=>c.id));
 const practice=majorCourses.find(c=>c.id===practiceId)||majorCourses[0]||courses[0];
 const courseState=(course:Course)=>readJournal(journals.find(j=>j.messages[0]?.text===journalMarker(course.id))?.messages||[]);
 const totalFoundationLessons=majorCourses.reduce((n,c)=>n+c.lessons.length,0);
 const completedFoundationLessons=majorCourses.reduce((n,c)=>n+c.lessons.filter(l=>courseState(c).completed.has(l.title)).length,0);
 const foundationPercent=totalFoundationLessons?Math.round(completedFoundationLessons/totalFoundationLessons*100):0;
 const projectedTerm=`Spring ${new Date().getFullYear()+4}`;
 const nextRequirements=major?.requirements.slice(0,3)||[];

 function choose(id:string){if(!signedIn){onSignup();return;}onSave(PROFILE_MARKER,'Unity student profile',[{role:'user',text:PROFILE_MARKER},{role:'user',text:JSON.stringify({majorId:id})}]);}
 function submit(){if(!signedIn||!ready)return;const attempt={id:crypto.randomUUID(),courseId:practice.id,correct:practice.lessons.filter((l,i)=>answers[i]===l.answer).length,total:practice.lessons.length,at:Date.now()};const marker=`[Unity practice: ${attempt.id}]`;onSave(marker,`Practice · ${practice.code}`,[{role:'user',text:marker},{role:'user',text:JSON.stringify(attempt)}]);setResult(attempt);}
 function download(){const text=['UNITY COLLEGE OF THE ARTS','PERSONAL LEARNING RECORD — NOT AN OFFICIAL TRANSCRIPT',`Generated: ${new Date().toLocaleDateString()}`,`Major: ${major?.degree||'Not selected'}`,`Practice GPA: ${summary.gpa===null?'Not yet available':summary.gpa.toFixed(2)}`,'Practice results and lesson progress are learning records; they do not certify earned academic credit.','',...summary.rows.map(r=>`${r.course.code} ${r.course.title}: ${r.best?`${Math.round(r.best.correct/r.best.total*100)}% / ${r.grade!.letter}`:'Not assessed'}; ${courseState(r.course).completed.size}/${r.course.lessons.length} lessons self-reported complete.`)].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='unity-personal-learning-record.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const serviceJournals=journals.filter(j=>j.messages[0]?.text.startsWith('[Unity service:'));

 return <div className="unity-portal">
 {view==='majors'&&major&&<>
  <p className="unity-kicker">MY ACADEMIC HOME</p>
  <h1>{major.degree}</h1>
  <p className="unity-portal-lead">Everything connected to your program lives here: your current semester, degree-plan progress, upcoming requirements, projected graduation, and shortcuts into your personalized courses.</p>

  <section className="unity-path-banner"><div><p className="unity-kicker">{major.school.toUpperCase()}</p><h2>{major.title}</h2><p>{major.description}</p></div><button onClick={()=>onNavigate('audit')}>Open degree audit ↗</button></section>

  <div className="unity-grade-overview">
   <article><span>FOUNDATION PROGRESS</span><strong>{foundationPercent}<small>%</small></strong><p>{completedFoundationLessons} of {totalFoundationLessons} foundation lessons completed.</p></article>
   <article><span>DEGREE PLAN</span><strong>{major.totalCredits}<small> credits</small></strong><p>Total credits represented in your program plan.</p></article>
   <article><span>PROJECTED GRADUATION</span><h2>{projectedTerm}</h2><p>Planning estimate based on a standard four-year path.</p></article>
  </div>

  <div className="unity-section-heading"><h2>Current semester</h2><span>{majorCourses.length} active foundation courses</span></div>
  <div className="unity-table-wrap"><table><caption>Your personalized course list</caption><thead><tr><th>Course</th><th>Progress</th><th>Status</th></tr></thead><tbody>{majorCourses.map(c=>{const count=c.lessons.filter(l=>courseState(c).completed.has(l.title)).length;return <tr key={c.id}><td>{c.code}<strong>{c.title}</strong></td><td>{count}/{c.lessons.length} lessons</td><td>{count===c.lessons.length?'Complete':count?'In progress':'Not started'}</td></tr>})}</tbody></table></div>
  <div className="unity-lesson-actions">{majorCourses.map(c=><button key={c.id} onClick={()=>onOpen(c)}>Open {c.code} ↗</button>)}</div>

  <div className="unity-section-heading"><h2>Next requirements</h2><button onClick={()=>onNavigate('audit')}>See full degree audit ↗</button></div>
  <div className="unity-major-grid">{nextRequirements.map((r,i)=><article key={r.id}><span className="unity-major-number">0{i+1}</span><p className="unity-kicker">{r.group.toUpperCase()}</p><h2>{r.label}</h2><p>{r.credits} credits in your degree plan.</p><h3>Status</h3><p>Planned</p></article>)}</div>

  <div className="unity-section-heading"><h2>Degree snapshot</h2><span>One place for your whole program</span></div>
  <section className="unity-path-banner"><div><p className="unity-kicker">PROGRAM SUMMARY</p><h2>{major.totalCredits}-credit degree plan</h2><p>{major.requirements.length} requirement groups · {majorCourses.length} current foundation courses · projected completion {projectedTerm}</p></div><button className="unity-primary" onClick={()=>onNavigate('audit')}>View degree audit</button></section>

  <div className="unity-info-note">Your My Major page and degree audit are planning tools inside Unity. Lesson completion and practice scores are shown separately from officially earned academic credit.</div>

  <div className="unity-section-heading"><h2>Your current foundation</h2><span>Personalized to {major.title}</span></div>
  <div className="unity-major-grid">{majorCourses.map((course,i)=>{const state=courseState(course);const completed=course.lessons.filter(l=>state.completed.has(l.title)).length;return <article key={course.id}><span className="unity-major-number">0{i+1}</span><p className="unity-kicker">{course.code}</p><h2>{course.title}</h2><p>{course.description}</p><h3>Progress</h3><p>{completed}/{course.lessons.length} lessons completed</p><progress value={completed} max={course.lessons.length} aria-label={`${course.title} lesson progress`}/><button className="unity-primary" onClick={()=>onOpen(course)}>{completed?'Continue course':'Start course'} ↗</button></article>})}</div>

  <div className="unity-lesson-actions"><button className="unity-primary" onClick={()=>onNavigate('audit')}>View degree audit</button><button onClick={()=>onNavigate('services')}>Student services</button><button onClick={()=>onService('advising')}>Academic advising with Lumi ✦</button></div>
 </>}

 {view==='majors'&&!major&&<>
  <p className="unity-kicker">CHOOSE YOUR ACADEMIC DIRECTION</p><h1>Build your student path.</h1><p className="unity-portal-lead">Choose a major to personalize your campus, course sequence, practice studio, degree-planning view, and Lumi guidance.</p><div className="unity-info-note">Your selection personalizes the current foundation experience. Degree-plan screens are planning tools and do not represent an accreditation or degree-award claim.</div>
  <div className="unity-major-grid">{majors.map((m,i)=><article key={m.id}><span className="unity-major-number">0{i+1}</span><p className="unity-kicker">{m.school}</p><h2>{m.degree}</h2><p>{m.description}</p><h3>You’ll work toward</h3><ul>{m.outcomes.map(o=><li key={o}>{o}</li>)}</ul><div className="unity-major-sequence">{m.courseIds.map((id,j)=><button key={id} onClick={()=>onOpen(courses.find(c=>c.id===id)!)}><span>{j+1}</span>{courses.find(c=>c.id===id)!.title} ↗</button>)}</div><p><strong>Portfolio focus:</strong> {m.project}</p><button className="unity-primary" disabled={!ready} onClick={()=>choose(m.id)}>{signedIn?'Choose this major':'Sign up to choose'}</button></article>)}</div>
 </>}

 {view==='audit'&&major&&<>
  <p className="unity-kicker">DEGREE AUDIT</p><h1>{major.degree}</h1><p className="unity-portal-lead">See your complete program framework in one place, then jump back into the foundation work that is active for you right now.</p>
  <div className="unity-grade-overview"><article><span>PROGRAM REQUIREMENTS</span><strong>{major.totalCredits}<small> credits</small></strong><p>Total credits represented in this degree plan.</p></article><article><span>FOUNDATION LESSONS</span><strong>{completedFoundationLessons}<small> / {totalFoundationLessons}</small></strong><p>{foundationPercent}% of your current foundation pathway complete.</p></article><article><span>ESTIMATED COMPLETION</span><h2>{projectedTerm}</h2><p>Estimated for planning; not an official graduation clearance.</p></article></div>
  <div className="unity-section-heading"><h2>Program requirement groups</h2><span>{major.requirements.reduce((n,r)=>n+r.credits,0)} credits planned</span></div>
  <div className="unity-table-wrap"><table><caption>Degree requirements · planning view</caption><thead><tr><th>Requirement</th><th>Credits</th><th>Status</th></tr></thead><tbody>{major.requirements.map(r=><tr key={r.id}><td><strong>{r.label}</strong><small>{r.group==='general'?'General education':r.group==='major'?'Major requirement':r.group==='elective'?'Elective requirement':'Capstone requirement'}</small></td><td>{r.credits}</td><td>Planned</td></tr>)}</tbody></table></div>
  <div className="unity-section-heading"><h2>Current foundation courses</h2><span>Personalized to {major.title}</span></div>
  <div className="unity-table-wrap"><table><caption>Foundation pathway</caption><thead><tr><th>Course</th><th>Lessons</th><th>Status</th></tr></thead><tbody>{majorCourses.map(c=>{const count=c.lessons.filter(l=>courseState(c).completed.has(l.title)).length;return <tr key={c.id}><td>{c.code}<strong>{c.title}</strong></td><td>{count}/{c.lessons.length}</td><td>{count===c.lessons.length?'Complete':count?'In progress':'Not started'}</td></tr>})}</tbody></table></div>
  <div className="unity-info-note">This audit organizes the Unity degree-plan concept and your saved foundation progress. It is not an official transcript, accreditation statement, or graduation clearance.</div>
  <div className="unity-lesson-actions"><button className="unity-primary" onClick={()=>onNavigate('majors')}>Back to My Major</button><button onClick={()=>onService('graduation')}>Graduation planning with Lumi ✦</button><button onClick={()=>onNavigate('services')}>Student services</button></div>
 </>}

 {view==='audit'&&!major&&<><p className="unity-kicker">DEGREE AUDIT</p><h1>Choose a major first.</h1><p className="unity-portal-lead">Once your program is selected, your degree-plan requirements and personalized foundation progress will appear here.</p><button className="unity-primary" onClick={()=>onNavigate('majors')}>Choose my major</button></>}

 {view==='practice'&&<><p className="unity-kicker">PRACTICE FOR YOUR MAJOR</p><h1>Your practice studio.</h1><p className="unity-portal-lead">Your practice library now follows {major?major.title:'your selected pathway'}. Try a course check, review what you missed, and ask Lumi to help with the next attempt.</p><div className="unity-practice-layout"><aside className="unity-practice-menu"><label htmlFor="practice-course">Choose a subject</label><select id="practice-course" value={practice.id} onChange={e=>{setPracticeId(e.target.value);setAnswers({});setResult(null);}}>{majorCourses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><p>{practice.lessons.length} questions · untimed<br/>All questions count equally.</p><button onClick={()=>onHelp(`Give me an ungraded practice exercise for ${practice.title}. Keep it connected to my ${major?.title||'current'} program. Ask one question at a time and wait for my answer.`)}>Practice freely with Lumi ✦</button><div className="unity-info-note">Only subjects connected to your current major appear here. Course checks contribute to your practice GPA; free practice and lesson completion do not.</div></aside><section className="unity-practice-paper"><h2>{practice.title}</h2>{result?<><div className="unity-practice-result"><strong>{Math.round(result.correct/result.total*100)}%</strong><p>{result.correct} of {result.total} correct</p></div>{practice.lessons.map((l,i)=><article className="unity-review-answer" key={l.title}><h3>{answers[i]===l.answer?'✓':'↻'} {l.question}</h3><p>Your answer: {l.options[answers[i]]}</p><p>Correct answer: {l.options[l.answer]}</p><p>{l.explanation}</p></article>)}<div className="unity-lesson-actions"><button className="unity-primary" onClick={()=>{setAnswers({});setResult(null);}}>Try again</button><button onClick={()=>onHelp(`Help me review ${practice.title}. I scored ${result.correct}/${result.total}. These concepts need practice: ${practice.lessons.filter((l,i)=>answers[i]!==l.answer).map(l=>l.title).join(', ')||'Give me a more challenging application exercise'}.`)}>Review with Lumi</button><button onClick={()=>onNavigate('grades')}>View grades →</button></div></>:<form onSubmit={e=>{e.preventDefault();submit();}}>{practice.lessons.map((l,i)=><fieldset className="unity-quiz" key={l.title}><legend>Question {i+1}</legend><p>{l.question}</p>{l.options.map((o,k)=><label key={o}><input required type="radio" name={`q${i}`} checked={answers[i]===k} onChange={()=>setAnswers({...answers,[i]:k})}/>{o}</label>)}</fieldset>)}{signedIn?<button className="unity-primary" disabled={!ready||Object.keys(answers).length!==practice.lessons.length}>Check & save my answers</button>:<button type="button" className="unity-primary" onClick={onSignup}>Create an account to save your score</button>}</form>}</section></div></>}

 {view==='grades'&&<><p className="unity-kicker">SEE HOW YOU’RE GROWING</p><h1>Your grades & learning record.</h1><div className="unity-grade-overview"><article><span>PRACTICE GPA</span><strong>{summary.gpa===null?'—':summary.gpa.toFixed(2)}<small> / 4.00</small></strong><p>{summary.gpa===null?'Complete a course check to get started.':'Based on your best course checks.'}</p></article><article><span>RECORDED ATTEMPTS</span><strong>{attempts.length}</strong><p>Retakes help you build confidence.</p></article><article><span>YOUR MAJOR</span><h2>{major?.degree||'Choose your program'}</h2><button onClick={()=>onNavigate('majors')}>{major?'Open My Major':'Choose a major'} ↗</button></article></div><div className="unity-info-note">Practice GPA is a personal study measure, not an official academic GPA. Each assessed course has equal weight. A = 90–100% (4.0), B = 80–89% (3.0), C = 70–79% (2.0), D = 60–69% (1.0), F = below 60% (0.0). Unassessed courses are excluded. Your selected major determines the courses included.</div><div className="unity-table-wrap"><table><caption>Course results · highest score retained</caption><thead><tr><th>Course</th><th>Score</th><th>Grade</th><th>Points</th></tr></thead><tbody>{summary.rows.map(r=><tr key={r.course.id}><td>{r.course.code}<strong>{r.course.title}</strong></td><td>{r.best?`${Math.round(r.best.correct/r.best.total*100)}%`:'Not assessed'}</td><td>{r.grade?.letter||'—'}</td><td>{r.grade?r.grade.points.toFixed(1):'—'}</td></tr>)}</tbody></table></div><div className="unity-lesson-actions"><button className="unity-primary" onClick={()=>onNavigate('practice')}>Go to practice</button><button onClick={download}>Download personal learning record</button></div>{attempts.length>0&&<details className="unity-attempts"><summary>All practice attempts ({attempts.length})</summary>{attempts.map(a=><p key={a.id}>{courses.find(c=>c.id===a.courseId)?.code} · {new Date(a.at).toLocaleString()} · {a.correct}/{a.total}</p>)}</details>}</>}

 {view==='services'&&<><p className="unity-kicker">SUPPORT FOR YOUR NEXT STEP</p><h1>Student services.</h1><p className="unity-portal-lead">Choose exactly what you need help with. Lumi opens in that service context and stays focused on the topic you selected.</p><div className="unity-info-note">Lumi provides AI guidance inside each service. Saved conversations are private to your account and are not automatically sent to a staffed support desk.</div><div className="unity-services-grid">{services.map(s=><button key={s.id} onClick={()=>onService(s.id)}><span>{s.icon}</span><div><strong>{s.title}</strong><small>{s.description}</small></div><b>↗</b></button>)}</div>
  {major&&<><div className="unity-section-heading"><h2>Program changes</h2><span>Registrar self-service</span></div><section className="unity-path-banner"><div><p className="unity-kicker">CURRENT PROGRAM</p><h2>{major.degree}</h2><p>Compare a different program with Lumi first, or select a new major here when you are ready to update your personalized pathway.</p></div><div><select aria-label="New major" value={pendingMajor} onChange={e=>setPendingMajor(e.target.value)}>{majors.map(m=><option key={m.id} value={m.id}>{m.degree}</option>)}</select><button className="unity-primary" disabled={!ready||pendingMajor===major.id} onClick={()=>choose(pendingMajor)}>Change my major</button></div></section></>}
  <div className="unity-section-heading"><h2>Your service conversations</h2><select aria-label="Filter service conversations" value={serviceFilter} onChange={e=>setServiceFilter(e.target.value)}><option value="all">All</option><option value="open">Open</option><option value="closed">Closed</option></select></div><div className="unity-service-history">{serviceJournals.filter(j=>serviceFilter==='all'||(j.messages.at(-1)?.text==='[Conversation closed]'?'closed':'open')===serviceFilter).map(j=>{const id=j.messages[0].text.split(']')[0].replace('[Unity service:','');const service=services.find(s=>s.id===id);const closed=j.messages.at(-1)?.text==='[Conversation closed]';return <div key={id}><button onClick={()=>onService(id)}><strong>{service?.title||'Support'}</strong><small>{closed?'Closed':'Open'} · {Math.max(0,j.messages.length-2)} messages</small></button><button disabled={!ready} onClick={()=>{const marker=`[Unity service:${id}]`;const messages=closed?j.messages.slice(0,-1):[...j.messages,{role:'user' as const,text:'[Conversation closed]'}];onSave(marker,`Services · ${service?.title||id}`,messages);}}>{closed?'Reopen':'Close'}</button></div>;})}{!serviceJournals.length&&<p>Your saved conversations will appear here after you send a message.</p>}</div></>}
 </div>;
}
